In [9]:
import pandas as pd
df = pd.read_csv('diabetes_prediction_dataset.csv',encoding='latin1')
df

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,Female,80.0,0,1,never,25.19,6.6,140,0
1,Female,54.0,0,0,No Info,27.32,6.6,80,0
2,Male,28.0,0,0,never,27.32,5.7,158,0
3,Female,36.0,0,0,current,23.45,5.0,155,0
4,Male,76.0,1,1,current,20.14,4.8,155,0
...,...,...,...,...,...,...,...,...,...
99995,Female,80.0,0,0,No Info,27.32,6.2,90,0
99996,Female,2.0,0,0,No Info,17.37,6.5,100,0
99997,Male,66.0,0,0,former,27.83,5.7,155,0
99998,Female,24.0,0,0,never,35.42,4.0,100,0
99999,Female,57.0,0,0,current,22.43,6.6,90,0

In [10]:
x= df.iloc[:,0:-1]
y= df.iloc[:,[-1]]

from sklearn.preprocessing import LabelEncoder as LE
encode = LE()
x['gender'] = encode.fit_transform(x['gender'])
x['smoking_history'] = encode.fit_transform(x['smoking_history'])

In [11]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=99)

In [12]:
import pickle
model = DecisionTreeClassifier(criterion="entropy")
model = model.fit(x_train,y_train)

with open('diabetes_decision_tree_model.pkl', 'wb') as model_file:
    pickle.dump(model, model_file)

y_pred = model.predict( x_test)
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [13]:
from sklearn import metrics
print("accuracy : ", metrics.accuracy_score(y_test,y_pred)*100)
# databaru = pd.read_csv('diabetes_dataset.csv')
# new_data = databaru.iloc[0:27,:-1]

accuracy :  95.33

In [14]:
databaru = pd.read_csv('testing.csv')
new_data = databaru.iloc[:,:]

new_data['gender'] = encode.fit_transform(new_data['gender'])
new_data['smoking_history'] = encode.fit_transform(new_data['smoking_history'])

new_pred = model.predict(new_data)
print("Hasil Prediksi:\n")
for nomor, prediksi in enumerate(new_pred, start=1):
    i = "diabetes" if prediksi == 1 else "Tidak diabetes"
    new_data_row = new_data.iloc[nomor-1]
    print(f"Data Baru ke-{nomor}:{new_data_row.tolist()} = {i}")

Hasil Prediksi:

Data Baru ke-1:[0.0, 46.0, 0.0, 1.0, 3.0, 25.19, 6.1, 155.0] = diabetes
Data Baru ke-2:[0.0, 67.0, 1.0, 1.0, 2.0, 27.32, 6.5, 200.0] = diabetes
Data Baru ke-3:[0.0, 44.0, 0.0, 0.0, 2.0, 15.94, 5.8, 145.0] = Tidak diabetes
Data Baru ke-4:[1.0, 21.0, 0.0, 1.0, 0.0, 15.8, 6.2, 126.0] = Tidak diabetes
Data Baru ke-5:[1.0, 30.0, 0.0, 0.0, 2.0, 27.01, 6.0, 100.0] = Tidak diabetes
Data Baru ke-6:[0.0, 59.0, 0.0, 1.0, 2.0, 27.32, 6.6, 85.0] = Tidak diabetes
Data Baru ke-7:[0.0, 27.0, 1.0, 0.0, 1.0, 22.19, 6.2, 85.0] = Tidak diabetes
Data Baru ke-8:[0.0, 59.0, 0.0, 1.0, 0.0, 27.45, 5.7, 130.0] = Tidak diabetes
Data Baru ke-9:[1.0, 19.0, 0.0, 0.0, 0.0, 17.98, 5.0, 200.0] = Tidak diabetes
Data Baru ke-10:[1.0, 13.0, 0.0, 1.0, 1.0, 27.32, 6.5, 260.0] = diabetes
Data Baru ke-11:[0.0, 56.0, 0.0, 0.0, 2.0, 27.32, 7.5, 200.0] = diabetes
Data Baru ke-12:[1.0, 2.0, 0.0, 1.0, 0.0, 54.7, 6.1, 160.0] = Tidak diabetes
Data Baru ke-13:[0.0, 7.0, 0.0, 0.0, 2.0, 36.05, 6.2, 130.0] = Tidak diabetes
Data Baru ke-14:[0.0, 3.0, 1.0, 0.0, 2.0, 25.69, 6.1, 159.0] = Tidak diabetes
Data Baru ke-15:[0.0, 30.0, 0.0, 1.0, 0.0, 27.32, 6.0, 160.0] = Tidak diabetes